services:
  - type: web
    name: receipt-tracker
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: ""   # Dockerfile handles build
    startCommand: ""   # Dockerfile CMD runs start.sh
    envVars:
      - key: YII_ENV
        value: prod
      - key: YII_DEBUG
        value: "0"
      - key: DB_DRIVER
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    postDeployCommand: |
      php yii migrate --interactive=0
